modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="aidens_technology"
version="1.3.0"
displayName="Aiden's Tech"
displayURL="https://modrinth.com/mod/aidens-tech"
logoFile="logo.png"
credits="|| Made by AidenAnimates ||"
authors="aidenanimates"
description="Guns n' stuff, man."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.aidens_technology]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.12,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.aidens_technology]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration